# -*- coding: utf-8 -*-
"""LungSegmentationJoHof.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VwXRCrrvWyVtRFf4hzDyo1ghcgal1krW
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!pip install git+https://github.com/JoHof/lungmask

from lungmask import mask
import SimpleITK as sitk
import cv2
import os

# #COVID-CT-MD and MosMed Database
# input_folder = '/content/drive/MyDrive/Dataset/COVID-CT-MD/NIfTI/Normal'
# output_folder = '/content/drive/MyDrive/Dataset/COVID-CT-MD/NIfTI/Normal_LungMask'
# input_folder = '/content/drive/MyDrive/Dataset/MosMed/CT-1'
# output_folder = '/content/drive/MyDrive/Dataset/MosMed/lung_masks'
# input_folder = '/content/drive/MyDrive/Dataset/COVID-CT-MD/NIfTI/CAP'
# output_folder = '/content/drive/MyDrive/Dataset/COVID-CT-MD/NIfTI/CAP_LungMask'

writer = sitk.ImageFileWriter()
writer.SetImageIO("NiftiImageIO")

def load_nii_format_volume (input_path):
    file_name = input_path.split("/")[-1].split(".")[0]
    print("[INFO] Loading ", file_name)

    reader = sitk.ImageFileReader()
    reader.SetImageIO("NiftiImageIO")
    reader.SetFileName(input_path)
    slides = reader.Execute()

    print("[INFO] Volume Size: ", slides.GetSize())
    return slides

def get_lung_mask(in_folder, out_folder, writer):
  for filename in os.listdir(in_folder):
    img = load_nii_format_volume(os.path.join(in_folder, filename))
    segmentation = mask.apply(img)
    filename_in = os.path.splitext((os.path.splitext(filename)[0]))
    writer.SetFileName(os.path.join(out_folder, f'{filename_in[0]}_lungmask_{filename_in[1]}.gz'))
    writer.Execute(sitk.GetImageFromArray(segmentation))

get_lung_mask(input_folder, output_folder, writer)

!ls -1 /content/drive/MyDrive/Dataset/MosMed/lung_masks | wc -l